### ISSUE TITLE
Merge with tasty-discover?

### ISSUE THREAD

**Issue by decentral1se** [minad/tasty-auto#1]
So, following from https://github.com/lwm/tasty-discover/pull/63:

> ... so if we work around these issues I am perfectly happy with merging the things together.

Still interested in merging together? I'd add you as collaborator over there so you could still have freedom to push changes. I think it still makes sense. I've fixed up licensing problems with https://github.com/lwm/tasty-discover/commit/07b0c47b6456a5d94a1b2d959ee15ae42c05e10f and moved to [your generator technique](https://github.com/lwm/tasty-discover/blob/master/library/Test/Tasty/Generator.hs), removing the `TemplateHaskell` dependency. A bit of copy/pasta, a bit of refactoring here and there - I learnt a bunch! :)

Thoughts?

**Comment by minad** [comment]
Ok, cool! I looked quickly through your code and would like to make some suggestions:

* I would remove the invalid show instance - https://github.com/lwm/tasty-discover/blob/master/library/Test/Tasty/Type.hs#L29. I think there is no reason to have it.
* Why not use deriving for https://github.com/lwm/tasty-discover/blob/master/library/Test/Tasty/Type.hs#L15
* You switched to concat for string concatenation, e.g., https://github.com/lwm/tasty-discover/blob/master/library/Test/Tasty/Discover.hs#L16. Is there a reason for that? I am asking since I am not sure what the best way is for fast string concatentation which doesn't give O(n^2) asymptotics. It hardly doesn't matter here, but I would like to know what the best style is.
* Maybe another small suggestion: I usually prefer if there is no Type module and the types are in the modules where they belong. Would it work if we have three modules here? Config, Test/Discover and Generator?

**Comment by minad** [comment]
If it is fully compatible in the end I would just deprecate tasty-auto and point to tasty-discover everywhere.

**Comment by minad** [comment]
And another one concerning the options: It seems to me that there are now three options which somehow control which modules to consider, --module-suffix, --ignore-module, --no-module-suffix
Would it be possible to generalize this somehow to one option which takes a globbing pattern or a regex, assuming you could do that without much code and using only base?

**Comment by decentral1se** [comment]
> I would remove the invalid show instance

Ah yes, it was for debugging but didn't help much after. Will do.

> Why not use deriving

Oh, yes, let's do that!

> You switched to concat for string concatenation

Yes, I found the `ShowS` pattern to be quite confusing to read and I was thinking of me maintaining the code :). I sometimes contribute on the [Stack](https://github.com/commercialhaskell/stack) project and they use the `concat <list of strings>` pattern extensively, which I found to be the most readable way. Regarding speed, it doesn't matter here, as you said.

>  I usually prefer if there is no Type module

Sure, I can do that. I had it before but then switched. Maybe it's better ...

> If it is fully compatible in the end I would just deprecate tasty-auto

Sure, makes sense.

> Would it be possible to generalize this somehow to one option

What would be the purpose? If you want to simplify, I'm not sure globbing/regex would achieve that. (EDIT: Could you show a mock example of what it would look like? Maybe it would be.) I only implemented them because people asked, so I am inclined to keep them as is.

**Comment by minad** [comment]
I thought, it would be nice to support something like
`--search-modules "*Test.hs" --ignore-modules "InvalidTest.hs"`. Multiple patterns should be possible. It would be more general and we would have one option less.

**Comment by decentral1se** [comment]
Ah yes, we could squeeze `--module-suffix` and `no-module-suffix` together, with a pattern. 

I created https://github.com/lwm/tasty-discover/issues/84 to keep track of that.

**Comment by decentral1se** [comment]
Ah, need to deal with this commit https://github.com/feuerbach/tasty/commit/b1c00224f4798e1d13eba8a205860ca2beb3d011 :) 

Feel free to close off whenever you make your decision! Thanks :+1:

**Comment by minad** [comment]
Ok, I deprecated tasty-auto. It would be cool if you could add me to your repo and maybe to the hackage owners (as fallback maintainer). However, I won't do anything without consulting you. We can discuss changes via PRs if those are necessary.

Please update the tasty readme and remove tasty-auto!

**Comment by decentral1se** [comment]
>  It would be cool if you could add me to your repo and maybe to the hackage owners (as fallback maintainer)

Done! Let me know if there are issues.

> However, I won't do anything without consulting you.

You're a collaborator now, it's your choice :)

Will update the README now.

**Comment by minad** [comment]
cool thx - i close this then!
